import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import NavBar from "@/app/ui/components/NavBar/NavBar";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/app/ui/theme";
import './globals.css';

export const viewport = {
    width: 'device-width',
    initialScale: 1,
  }

export const metadata = {
    title: "Personal Website", 
    description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
                <NavBar/>
                {children}
            </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
